---
- hosts: all


  tasks:

    - name: Download rust installer
      shell: curl https://sh.rustup.rs -sSf > /tmp/install_rust.sh
      args:
        creates: /tmp/install_rust.sh

    - name: Install rust
      shell: sh /tmp/install_rust.sh -y
      args:
        creates: ~/.cargo/bin/rustc

