---
- hosts: all


  tasks:

    - name: Clone webrtc samples repo
      git:
        repo: https://github.com/webrtc/samples
        dest: ~/git-checkouts/webrtc-samples

    - name: Create directory for firefox builds
      shell: mkdir -p ~/no_tm_backup/MozillaBuilds/obj/opt ~/no_tm_backup/MozillaBuilds/obj/deb ~/no_tm_backup/MozillaBuilds/obj/debopt ~/no_tm_backup/MozillaBuilds/scratch_user ~/no_tm_backup/MozillaBuilds/ccache ~/no_tm_backup/MozillaBuilds/sccache
      ignore_errors: true
