#!/bin/sh

# Uncomment the following two lines for normal desktop:
#unset SESSION_MANAGER
# exec /etc/X11/xinit/xinitrc

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &
#x-terminal-emulator -geometry 1280x930 -ls -title "$VNCDESKTOP Desktop" &
x-window-manager &

export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
gnome-session --session=ubuntu -geometry 1280x930 -ls -title "$VNCDESKTOP Desktop" &

gnome-panel &
#nautilus &
xfce4-terminal &
gnome-settings-daemon &

